# Generated by Django 4.2.2 on 2023-10-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='theme',
            field=models.CharField(choices=[('theme_1', 'tw-theme-1'), ('theme_2', 'tw-theme-2'), ('theme_3', 'tw-theme-3'), ('theme_4', 'tw-theme-4')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.label'),
        ),
    ]
