# Generated by Django 4.2.2 on 2023-10-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_label_theme_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='theme',
            field=models.CharField(choices=[('theme_1', 'theme-1'), ('theme_2', 'theme-2'), ('theme_3', 'theme-3'), ('theme_4', 'theme-4')], max_length=128, null=True),
        ),
    ]
