# Generated by Django 4.2.2 on 2023-10-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
